//*
// @Author: kamalyes 501893067@qq.com
// @Date: 2026-07-18 00:00:00
// @LastEditors: kamalyes 501893067@qq.com
// @LastEditTime: 2026-07-18 00:00:00
// @FilePath: \go-wsc\proto\node.proto
// @Description: 节点间 gRPC 通信协议定义
//
// 每个 WebSocket Hub 节点同时运行 gRPC 服务端与客户端，支持点对点直连通信
// 相比 Redis PubSub 广播模式，gRPC 直连可精确路由到目标节点，降低延迟
// 当 gRPC 未启用或目标地址未知时，自动降级到 Redis PubSub
//
// 路由元数据设计（namespace / group_ids）：
//   - 通过 gRPC metadata headers 传递（非 proto 字段），避免消息体膨胀
//   - 定义位于独立 routing 包（github.com/kamalyes/go-wsc/routing），全项目共用
//   - x-routing-namespace：命名空间ID（空表示全局，默认 "default"）
//   - x-routing-group-ids：群组ID列表（逗号分隔；空表示无群组操作）
//   - 客户端注入：routing.InjectToOutgoingMetadata（从 context 提取并写入 metadata）
//   - 服务端恢复：routing.RestoreFromIncomingMetadata（从 metadata 读取并注入 context）
//
// Copyright (c) 2026 by kamalyes, All Rights Reserved.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.24.3
// source: node.proto

package wscpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DispatchOperation 微批投递操作类型（替代裸字符串，枚举语义 + 线型 varint 紧凑编码）
// [EN] Micro-batch delivery operation type (enum instead of raw string).
type DispatchOperation int32

const (
	DispatchOperation_DISPATCH_OPERATION_UNSPECIFIED DispatchOperation = 0 // 未指定（默认值，非法操作）| [EN] Unspecified (default, invalid)
	DispatchOperation_DISPATCH_SEND_MESSAGE          DispatchOperation = 1 // 点对点投递 | [EN] Point-to-point delivery
	DispatchOperation_DISPATCH_KICK_USER             DispatchOperation = 2 // 踢人 | [EN] Kick user
	DispatchOperation_DISPATCH_GROUP_BROADCAST       DispatchOperation = 3 // 群组广播（单群组语义，多群组由发送端拆分为多条 item）| [EN] Group broadcast (single-group)
	DispatchOperation_DISPATCH_OBSERVER_NOTIFY       DispatchOperation = 4 // 观察者通知 | [EN] Observer notification
	DispatchOperation_DISPATCH_BROADCAST             DispatchOperation = 5 // 全局/命名空间广播 | [EN] Global/namespace broadcast
)

// Enum value maps for DispatchOperation.
var (
	DispatchOperation_name = map[int32]string{
		0: "DISPATCH_OPERATION_UNSPECIFIED",
		1: "DISPATCH_SEND_MESSAGE",
		2: "DISPATCH_KICK_USER",
		3: "DISPATCH_GROUP_BROADCAST",
		4: "DISPATCH_OBSERVER_NOTIFY",
		5: "DISPATCH_BROADCAST",
	}
	DispatchOperation_value = map[string]int32{
		"DISPATCH_OPERATION_UNSPECIFIED": 0,
		"DISPATCH_SEND_MESSAGE":          1,
		"DISPATCH_KICK_USER":             2,
		"DISPATCH_GROUP_BROADCAST":       3,
		"DISPATCH_OBSERVER_NOTIFY":       4,
		"DISPATCH_BROADCAST":             5,
	}
)

func (x DispatchOperation) Enum() *DispatchOperation {
	p := new(DispatchOperation)
	*p = x
	return p
}

func (x DispatchOperation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DispatchOperation) Descriptor() protoreflect.EnumDescriptor {
	return file_node_proto_enumTypes[0].Descriptor()
}

func (DispatchOperation) Type() protoreflect.EnumType {
	return &file_node_proto_enumTypes[0]
}

func (x DispatchOperation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DispatchOperation.Descriptor instead.
func (DispatchOperation) EnumDescriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{0}
}

// SendToUserRequest 发送消息请求
// [EN] Send message request
type SendToUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                // 目标用户ID | [EN] Target user ID
	MessageData   []byte                 `protobuf:"bytes,2,opt,name=message_data,json=messageData,proto3" json:"message_data,omitempty"` // 序列化后的 HubMessageProto | [EN] Serialized HubMessageProto
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendToUserRequest) Reset() {
	*x = SendToUserRequest{}
	mi := &file_node_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendToUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendToUserRequest) ProtoMessage() {}

func (x *SendToUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendToUserRequest.ProtoReflect.Descriptor instead.
func (*SendToUserRequest) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{0}
}

func (x *SendToUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SendToUserRequest) GetMessageData() []byte {
	if x != nil {
		return x.MessageData
	}
	return nil
}

// SendToUserResponse 发送消息响应
// [EN] Send message response
type SendToUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`                         // 是否投递成功 | [EN] Whether delivery succeeded
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`                              // 失败原因（成功时为空） | [EN] Failure reason (empty on success)
	UserOnline    bool                   `protobuf:"varint,3,opt,name=user_online,json=userOnline,proto3" json:"user_online,omitempty"` // 用户是否在本节点在线 | [EN] Whether user is online on this node
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendToUserResponse) Reset() {
	*x = SendToUserResponse{}
	mi := &file_node_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendToUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendToUserResponse) ProtoMessage() {}

func (x *SendToUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendToUserResponse.ProtoReflect.Descriptor instead.
func (*SendToUserResponse) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{1}
}

func (x *SendToUserResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SendToUserResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *SendToUserResponse) GetUserOnline() bool {
	if x != nil {
		return x.UserOnline
	}
	return false
}

// CheckUsersOnlineRequest 批量检查在线状态请求
// [EN] Batch online check request
type CheckUsersOnlineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []string               `protobuf:"bytes,1,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"` // 待检查的用户ID列表 | [EN] User IDs to check
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckUsersOnlineRequest) Reset() {
	*x = CheckUsersOnlineRequest{}
	mi := &file_node_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckUsersOnlineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckUsersOnlineRequest) ProtoMessage() {}

func (x *CheckUsersOnlineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckUsersOnlineRequest.ProtoReflect.Descriptor instead.
func (*CheckUsersOnlineRequest) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{2}
}

func (x *CheckUsersOnlineRequest) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

// CheckUsersOnlineResponse 批量检查在线状态响应
// [EN] Batch online check response
type CheckUsersOnlineResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OnlineUsers   map[string]bool        `protobuf:"bytes,1,rep,name=online_users,json=onlineUsers,proto3" json:"online_users,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // userID → 是否在本节点在线 | [EN] userID → online on this node
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckUsersOnlineResponse) Reset() {
	*x = CheckUsersOnlineResponse{}
	mi := &file_node_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckUsersOnlineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckUsersOnlineResponse) ProtoMessage() {}

func (x *CheckUsersOnlineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckUsersOnlineResponse.ProtoReflect.Descriptor instead.
func (*CheckUsersOnlineResponse) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{3}
}

func (x *CheckUsersOnlineResponse) GetOnlineUsers() map[string]bool {
	if x != nil {
		return x.OnlineUsers
	}
	return nil
}

// BroadcastGroupRequest 群组广播请求
// 路由元数据（namespace, group_ids）通过 gRPC metadata 传递，参见文件头注释
// [EN] Group broadcast request. Routing metadata via gRPC metadata headers, see file header.
type BroadcastGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageData   []byte                 `protobuf:"bytes,1,opt,name=message_data,json=messageData,proto3" json:"message_data,omitempty"`        // 序列化后的 HubMessageProto | [EN] Serialized HubMessageProto
	ExcludeSender bool                   `protobuf:"varint,2,opt,name=exclude_sender,json=excludeSender,proto3" json:"exclude_sender,omitempty"` // 是否排除发送者 | [EN] Whether to exclude sender
	SenderId      string                 `protobuf:"bytes,3,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`                 // 发送者用户ID（用于排除） | [EN] Sender user ID (for exclusion)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BroadcastGroupRequest) Reset() {
	*x = BroadcastGroupRequest{}
	mi := &file_node_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BroadcastGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastGroupRequest) ProtoMessage() {}

func (x *BroadcastGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastGroupRequest.ProtoReflect.Descriptor instead.
func (*BroadcastGroupRequest) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{4}
}

func (x *BroadcastGroupRequest) GetMessageData() []byte {
	if x != nil {
		return x.MessageData
	}
	return nil
}

func (x *BroadcastGroupRequest) GetExcludeSender() bool {
	if x != nil {
		return x.ExcludeSender
	}
	return false
}

func (x *BroadcastGroupRequest) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

// BroadcastGroupResponse 群组广播响应
// [EN] Group broadcast response
type BroadcastGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Delivered     int32                  `protobuf:"varint,1,opt,name=delivered,proto3" json:"delivered,omitempty"` // 本节点投递数量 | [EN] Delivered count on this node
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BroadcastGroupResponse) Reset() {
	*x = BroadcastGroupResponse{}
	mi := &file_node_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BroadcastGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastGroupResponse) ProtoMessage() {}

func (x *BroadcastGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastGroupResponse.ProtoReflect.Descriptor instead.
func (*BroadcastGroupResponse) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{5}
}

func (x *BroadcastGroupResponse) GetDelivered() int32 {
	if x != nil {
		return x.Delivered
	}
	return 0
}

// NotifyObserversRequest 观察者通知请求
// 路由元数据（namespace, group_ids）通过 gRPC metadata 传递，参见文件头注释
// [EN] Observer notification request. Routing metadata via gRPC metadata headers, see file header.
type NotifyObserversRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageData   []byte                 `protobuf:"bytes,1,opt,name=message_data,json=messageData,proto3" json:"message_data,omitempty"` // 序列化后的 HubMessageProto | [EN] Serialized HubMessageProto
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyObserversRequest) Reset() {
	*x = NotifyObserversRequest{}
	mi := &file_node_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyObserversRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyObserversRequest) ProtoMessage() {}

func (x *NotifyObserversRequest) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyObserversRequest.ProtoReflect.Descriptor instead.
func (*NotifyObserversRequest) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{6}
}

func (x *NotifyObserversRequest) GetMessageData() []byte {
	if x != nil {
		return x.MessageData
	}
	return nil
}

// NotifyObserversResponse 观察者通知响应
// [EN] Observer notification response
type NotifyObserversResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notified      int32                  `protobuf:"varint,1,opt,name=notified,proto3" json:"notified,omitempty"` // 本节点通知数量 | [EN] Notified count on this node
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyObserversResponse) Reset() {
	*x = NotifyObserversResponse{}
	mi := &file_node_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyObserversResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyObserversResponse) ProtoMessage() {}

func (x *NotifyObserversResponse) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyObserversResponse.ProtoReflect.Descriptor instead.
func (*NotifyObserversResponse) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{7}
}

func (x *NotifyObserversResponse) GetNotified() int32 {
	if x != nil {
		return x.Notified
	}
	return 0
}

// KickUserRequest 踢人请求
// [EN] Kick user request
type KickUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 目标用户ID | [EN] Target user ID
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`               // 踢出原因 | [EN] Kick reason
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KickUserRequest) Reset() {
	*x = KickUserRequest{}
	mi := &file_node_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KickUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickUserRequest) ProtoMessage() {}

func (x *KickUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickUserRequest.ProtoReflect.Descriptor instead.
func (*KickUserRequest) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{8}
}

func (x *KickUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *KickUserRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// KickUserResponse 踢人响应
// [EN] Kick user response
type KickUserResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Success           bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`                                              // 是否成功 | [EN] Whether kick succeeded
	KickedConnections int32                  `protobuf:"varint,2,opt,name=kicked_connections,json=kickedConnections,proto3" json:"kicked_connections,omitempty"` // 踢出的连接数 | [EN] Kicked connection count
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *KickUserResponse) Reset() {
	*x = KickUserResponse{}
	mi := &file_node_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KickUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickUserResponse) ProtoMessage() {}

func (x *KickUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickUserResponse.ProtoReflect.Descriptor instead.
func (*KickUserResponse) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{9}
}

func (x *KickUserResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *KickUserResponse) GetKickedConnections() int32 {
	if x != nil {
		return x.KickedConnections
	}
	return 0
}

// PingRequest 健康检查请求
// [EN] Ping request
type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"` // 发起方节点ID | [EN] Source node ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_node_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{10}
}

func (x *PingRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

// PingResponse 健康检查响应
// [EN] Ping response
type PingResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	NodeId            string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`                                   // 响应方节点ID | [EN] Responder node ID
	ActiveConnections int64                  `protobuf:"varint,2,opt,name=active_connections,json=activeConnections,proto3" json:"active_connections,omitempty"` // 活跃连接数 | [EN] Active connection count
	Healthy           bool                   `protobuf:"varint,3,opt,name=healthy,proto3" json:"healthy,omitempty"`                                              // 节点是否健康 | [EN] Whether node is healthy
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_node_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{11}
}

func (x *PingResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *PingResponse) GetActiveConnections() int64 {
	if x != nil {
		return x.ActiveConnections
	}
	return 0
}

func (x *PingResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

// DispatchItem 单条跨节点投递指令（微批合帧最小单元）
// 路由信封（app_id / namespace / group_ids）内嵌于指令体，
// 不依赖 gRPC metadata，支持同批多租户 / 多群组异构合帧
// [EN] A single inter-node delivery instruction (micro-batch unit). Routing envelope embedded.
type DispatchItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operation     DispatchOperation      `protobuf:"varint,1,opt,name=operation,proto3,enum=wscpb.DispatchOperation" json:"operation,omitempty"` // 操作类型 | [EN] Operation type
	AppId         string                 `protobuf:"bytes,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`                          // 路由信封 appID（最上层隔离维度）| [EN] Routing envelope appID
	Namespace     string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`                               // 路由信封 namespace（空=全局/通配）| [EN] Routing envelope namespace
	GroupIds      []string               `protobuf:"bytes,4,rep,name=group_ids,json=groupIds,proto3" json:"group_ids,omitempty"`                 // 路由信封 groupIDs（群组维度）| [EN] Routing envelope group IDs
	TargetUserId  string                 `protobuf:"bytes,5,opt,name=target_user_id,json=targetUserId,proto3" json:"target_user_id,omitempty"`   // 目标用户（send_message/kick_user 使用）| [EN] Target user ID
	Reason        string                 `protobuf:"bytes,6,opt,name=reason,proto3" json:"reason,omitempty"`                                     // 辅助信息（kick_user 踢人原因）| [EN] Auxiliary info (kick reason)
	MessageData   []byte                 `protobuf:"bytes,7,opt,name=message_data,json=messageData,proto3" json:"message_data,omitempty"`        // 序列化后的 HubMessageProto | [EN] Serialized HubMessageProto
	ExcludeSender bool                   `protobuf:"varint,8,opt,name=exclude_sender,json=excludeSender,proto3" json:"exclude_sender,omitempty"` // 群组广播是否排除发送者 | [EN] Whether to exclude sender
	SenderId      string                 `protobuf:"bytes,9,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`                 // 发送者用户ID（用于排除）| [EN] Sender user ID (for exclusion)
	TraceId       string                 `protobuf:"bytes,10,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`                   // 全链路追踪ID（每条 item 各自携带，跨节点串联日志）| [EN] Trace ID for full-link correlation
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DispatchItem) Reset() {
	*x = DispatchItem{}
	mi := &file_node_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispatchItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchItem) ProtoMessage() {}

func (x *DispatchItem) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchItem.ProtoReflect.Descriptor instead.
func (*DispatchItem) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{12}
}

func (x *DispatchItem) GetOperation() DispatchOperation {
	if x != nil {
		return x.Operation
	}
	return DispatchOperation_DISPATCH_OPERATION_UNSPECIFIED
}

func (x *DispatchItem) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *DispatchItem) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *DispatchItem) GetGroupIds() []string {
	if x != nil {
		return x.GroupIds
	}
	return nil
}

func (x *DispatchItem) GetTargetUserId() string {
	if x != nil {
		return x.TargetUserId
	}
	return ""
}

func (x *DispatchItem) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *DispatchItem) GetMessageData() []byte {
	if x != nil {
		return x.MessageData
	}
	return nil
}

func (x *DispatchItem) GetExcludeSender() bool {
	if x != nil {
		return x.ExcludeSender
	}
	return false
}

func (x *DispatchItem) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *DispatchItem) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

// DispatchResult 单条投递结果（与 DispatchItem 一一对应）
// [EN] Per-item dispatch result
type DispatchResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`                         // send_message: 是否投递成功; kick_user: 是否成功 | [EN] Whether succeeded
	UserOnline    bool                   `protobuf:"varint,2,opt,name=user_online,json=userOnline,proto3" json:"user_online,omitempty"` // send_message 专用: 用户是否在线 | [EN] Whether user online (send only)
	Count         int32                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`                             // 投递数/踢出连接数/通知数 | [EN] delivered/kicked/notified count
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`                              // 失败原因（成功时为空）| [EN] Failure reason (empty on success)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DispatchResult) Reset() {
	*x = DispatchResult{}
	mi := &file_node_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispatchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchResult) ProtoMessage() {}

func (x *DispatchResult) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchResult.ProtoReflect.Descriptor instead.
func (*DispatchResult) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{13}
}

func (x *DispatchResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DispatchResult) GetUserOnline() bool {
	if x != nil {
		return x.UserOnline
	}
	return false
}

func (x *DispatchResult) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *DispatchResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// BatchDispatchRequest 微批投递请求（多条指令合帧）
// [EN] Micro-batch dispatch request
type BatchDispatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*DispatchItem        `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"` // 待投递指令列表 | [EN] Dispatch instructions
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchDispatchRequest) Reset() {
	*x = BatchDispatchRequest{}
	mi := &file_node_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchDispatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchDispatchRequest) ProtoMessage() {}

func (x *BatchDispatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchDispatchRequest.ProtoReflect.Descriptor instead.
func (*BatchDispatchRequest) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{14}
}

func (x *BatchDispatchRequest) GetItems() []*DispatchItem {
	if x != nil {
		return x.Items
	}
	return nil
}

// BatchDispatchResponse 微批投递响应（结果与请求 items 一一对应）
// [EN] Micro-batch dispatch response
type BatchDispatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*DispatchResult      `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"` // 逐条结果 | [EN] Per-item results
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchDispatchResponse) Reset() {
	*x = BatchDispatchResponse{}
	mi := &file_node_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchDispatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchDispatchResponse) ProtoMessage() {}

func (x *BatchDispatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchDispatchResponse.ProtoReflect.Descriptor instead.
func (*BatchDispatchResponse) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{15}
}

func (x *BatchDispatchResponse) GetResults() []*DispatchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

var File_node_proto protoreflect.FileDescriptor

const file_node_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"node.proto\x12\x05wscpb\"O\n" +
	"\x11SendToUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12!\n" +
	"\fmessage_data\x18\x02 \x01(\fR\vmessageData\"e\n" +
	"\x12SendToUserResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x1f\n" +
	"\vuser_online\x18\x03 \x01(\bR\n" +
	"userOnline\"4\n" +
	"\x17CheckUsersOnlineRequest\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\tR\auserIds\"\xaf\x01\n" +
	"\x18CheckUsersOnlineResponse\x12S\n" +
	"\fonline_users\x18\x01 \x03(\v20.wscpb.CheckUsersOnlineResponse.OnlineUsersEntryR\vonlineUsers\x1a>\n" +
	"\x10OnlineUsersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01\"~\n" +
	"\x15BroadcastGroupRequest\x12!\n" +
	"\fmessage_data\x18\x01 \x01(\fR\vmessageData\x12%\n" +
	"\x0eexclude_sender\x18\x02 \x01(\bR\rexcludeSender\x12\x1b\n" +
	"\tsender_id\x18\x03 \x01(\tR\bsenderId\"6\n" +
	"\x16BroadcastGroupResponse\x12\x1c\n" +
	"\tdelivered\x18\x01 \x01(\x05R\tdelivered\";\n" +
	"\x16NotifyObserversRequest\x12!\n" +
	"\fmessage_data\x18\x01 \x01(\fR\vmessageData\"5\n" +
	"\x17NotifyObserversResponse\x12\x1a\n" +
	"\bnotified\x18\x01 \x01(\x05R\bnotified\"B\n" +
	"\x0fKickUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"[\n" +
	"\x10KickUserResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12-\n" +
	"\x12kicked_connections\x18\x02 \x01(\x05R\x11kickedConnections\"&\n" +
	"\vPingRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"p\n" +
	"\fPingResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12-\n" +
	"\x12active_connections\x18\x02 \x01(\x03R\x11activeConnections\x12\x18\n" +
	"\ahealthy\x18\x03 \x01(\bR\ahealthy\"\xd8\x02\n" +
	"\fDispatchItem\x126\n" +
	"\toperation\x18\x01 \x01(\x0e2\x18.wscpb.DispatchOperationR\toperation\x12\x15\n" +
	"\x06app_id\x18\x02 \x01(\tR\x05appId\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12\x1b\n" +
	"\tgroup_ids\x18\x04 \x03(\tR\bgroupIds\x12$\n" +
	"\x0etarget_user_id\x18\x05 \x01(\tR\ftargetUserId\x12\x16\n" +
	"\x06reason\x18\x06 \x01(\tR\x06reason\x12!\n" +
	"\fmessage_data\x18\a \x01(\fR\vmessageData\x12%\n" +
	"\x0eexclude_sender\x18\b \x01(\bR\rexcludeSender\x12\x1b\n" +
	"\tsender_id\x18\t \x01(\tR\bsenderId\x12\x19\n" +
	"\btrace_id\x18\n" +
	" \x01(\tR\atraceId\"w\n" +
	"\x0eDispatchResult\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1f\n" +
	"\vuser_online\x18\x02 \x01(\bR\n" +
	"userOnline\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x05R\x05count\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"A\n" +
	"\x14BatchDispatchRequest\x12)\n" +
	"\x05items\x18\x01 \x03(\v2\x13.wscpb.DispatchItemR\x05items\"H\n" +
	"\x15BatchDispatchResponse\x12/\n" +
	"\aresults\x18\x01 \x03(\v2\x15.wscpb.DispatchResultR\aresults*\xbe\x01\n" +
	"\x11DispatchOperation\x12\"\n" +
	"\x1eDISPATCH_OPERATION_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15DISPATCH_SEND_MESSAGE\x10\x01\x12\x16\n" +
	"\x12DISPATCH_KICK_USER\x10\x02\x12\x1c\n" +
	"\x18DISPATCH_GROUP_BROADCAST\x10\x03\x12\x1c\n" +
	"\x18DISPATCH_OBSERVER_NOTIFY\x10\x04\x12\x16\n" +
	"\x12DISPATCH_BROADCAST\x10\x052\x80\x04\n" +
	"\vNodeService\x12A\n" +
	"\n" +
	"SendToUser\x12\x18.wscpb.SendToUserRequest\x1a\x19.wscpb.SendToUserResponse\x12S\n" +
	"\x10CheckUsersOnline\x12\x1e.wscpb.CheckUsersOnlineRequest\x1a\x1f.wscpb.CheckUsersOnlineResponse\x12M\n" +
	"\x0eBroadcastGroup\x12\x1c.wscpb.BroadcastGroupRequest\x1a\x1d.wscpb.BroadcastGroupResponse\x12P\n" +
	"\x0fNotifyObservers\x12\x1d.wscpb.NotifyObserversRequest\x1a\x1e.wscpb.NotifyObserversResponse\x12;\n" +
	"\bKickUser\x12\x16.wscpb.KickUserRequest\x1a\x17.wscpb.KickUserResponse\x12/\n" +
	"\x04Ping\x12\x12.wscpb.PingRequest\x1a\x13.wscpb.PingResponse\x12J\n" +
	"\rBatchDispatch\x12\x1b.wscpb.BatchDispatchRequest\x1a\x1c.wscpb.BatchDispatchResponseB,Z*github.com/kamalyes/go-wsc/models/pb;wscpbb\x06proto3"

var (
	file_node_proto_rawDescOnce sync.Once
	file_node_proto_rawDescData []byte
)

func file_node_proto_rawDescGZIP() []byte {
	file_node_proto_rawDescOnce.Do(func() {
		file_node_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_node_proto_rawDesc), len(file_node_proto_rawDesc)))
	})
	return file_node_proto_rawDescData
}

var file_node_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_node_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_node_proto_goTypes = []any{
	(DispatchOperation)(0),           // 0: wscpb.DispatchOperation
	(*SendToUserRequest)(nil),        // 1: wscpb.SendToUserRequest
	(*SendToUserResponse)(nil),       // 2: wscpb.SendToUserResponse
	(*CheckUsersOnlineRequest)(nil),  // 3: wscpb.CheckUsersOnlineRequest
	(*CheckUsersOnlineResponse)(nil), // 4: wscpb.CheckUsersOnlineResponse
	(*BroadcastGroupRequest)(nil),    // 5: wscpb.BroadcastGroupRequest
	(*BroadcastGroupResponse)(nil),   // 6: wscpb.BroadcastGroupResponse
	(*NotifyObserversRequest)(nil),   // 7: wscpb.NotifyObserversRequest
	(*NotifyObserversResponse)(nil),  // 8: wscpb.NotifyObserversResponse
	(*KickUserRequest)(nil),          // 9: wscpb.KickUserRequest
	(*KickUserResponse)(nil),         // 10: wscpb.KickUserResponse
	(*PingRequest)(nil),              // 11: wscpb.PingRequest
	(*PingResponse)(nil),             // 12: wscpb.PingResponse
	(*DispatchItem)(nil),             // 13: wscpb.DispatchItem
	(*DispatchResult)(nil),           // 14: wscpb.DispatchResult
	(*BatchDispatchRequest)(nil),     // 15: wscpb.BatchDispatchRequest
	(*BatchDispatchResponse)(nil),    // 16: wscpb.BatchDispatchResponse
	nil,                              // 17: wscpb.CheckUsersOnlineResponse.OnlineUsersEntry
}
var file_node_proto_depIdxs = []int32{
	17, // 0: wscpb.CheckUsersOnlineResponse.online_users:type_name -> wscpb.CheckUsersOnlineResponse.OnlineUsersEntry
	0,  // 1: wscpb.DispatchItem.operation:type_name -> wscpb.DispatchOperation
	13, // 2: wscpb.BatchDispatchRequest.items:type_name -> wscpb.DispatchItem
	14, // 3: wscpb.BatchDispatchResponse.results:type_name -> wscpb.DispatchResult
	1,  // 4: wscpb.NodeService.SendToUser:input_type -> wscpb.SendToUserRequest
	3,  // 5: wscpb.NodeService.CheckUsersOnline:input_type -> wscpb.CheckUsersOnlineRequest
	5,  // 6: wscpb.NodeService.BroadcastGroup:input_type -> wscpb.BroadcastGroupRequest
	7,  // 7: wscpb.NodeService.NotifyObservers:input_type -> wscpb.NotifyObserversRequest
	9,  // 8: wscpb.NodeService.KickUser:input_type -> wscpb.KickUserRequest
	11, // 9: wscpb.NodeService.Ping:input_type -> wscpb.PingRequest
	15, // 10: wscpb.NodeService.BatchDispatch:input_type -> wscpb.BatchDispatchRequest
	2,  // 11: wscpb.NodeService.SendToUser:output_type -> wscpb.SendToUserResponse
	4,  // 12: wscpb.NodeService.CheckUsersOnline:output_type -> wscpb.CheckUsersOnlineResponse
	6,  // 13: wscpb.NodeService.BroadcastGroup:output_type -> wscpb.BroadcastGroupResponse
	8,  // 14: wscpb.NodeService.NotifyObservers:output_type -> wscpb.NotifyObserversResponse
	10, // 15: wscpb.NodeService.KickUser:output_type -> wscpb.KickUserResponse
	12, // 16: wscpb.NodeService.Ping:output_type -> wscpb.PingResponse
	16, // 17: wscpb.NodeService.BatchDispatch:output_type -> wscpb.BatchDispatchResponse
	11, // [11:18] is the sub-list for method output_type
	4,  // [4:11] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_node_proto_init() }
func file_node_proto_init() {
	if File_node_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_node_proto_rawDesc), len(file_node_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_node_proto_goTypes,
		DependencyIndexes: file_node_proto_depIdxs,
		EnumInfos:         file_node_proto_enumTypes,
		MessageInfos:      file_node_proto_msgTypes,
	}.Build()
	File_node_proto = out.File
	file_node_proto_goTypes = nil
	file_node_proto_depIdxs = nil
}
