//*
// @Author: kamalyes 501893067@qq.com
// @Date: 2026-07-18 00:00:00
// @LastEditors: kamalyes 501893067@qq.com
// @LastEditTime: 2026-07-18 00:00:00
// @FilePath: \go-wsc\proto\node.proto
// @Description: 节点间 gRPC 通信协议定义
//
// 每个 WebSocket Hub 节点同时运行 gRPC 服务端与客户端，支持点对点直连通信
// 相比 Redis PubSub 广播模式，gRPC 直连可精确路由到目标节点，降低延迟
// 当 gRPC 未启用或目标地址未知时，自动降级到 Redis PubSub
//
// 路由元数据设计（namespace / group_ids）：
//   - 通过 gRPC metadata headers 传递（非 proto 字段），避免消息体膨胀
//   - 定义位于独立 routing 包（github.com/kamalyes/go-wsc/routing），全项目共用
//   - x-routing-namespace：命名空间ID（空表示全局，默认 "default"）
//   - x-routing-group-ids：群组ID列表（逗号分隔；空表示无群组操作）
//   - 客户端注入：routing.InjectToOutgoingMetadata（从 context 提取并写入 metadata）
//   - 服务端恢复：routing.RestoreFromIncomingMetadata（从 metadata 读取并注入 context）
//
// Copyright (c) 2026 by kamalyes, All Rights Reserved.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.24.3
// source: node.proto

package wscpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NodeService_SendToUser_FullMethodName       = "/wscpb.NodeService/SendToUser"
	NodeService_CheckUsersOnline_FullMethodName = "/wscpb.NodeService/CheckUsersOnline"
	NodeService_BroadcastGroup_FullMethodName   = "/wscpb.NodeService/BroadcastGroup"
	NodeService_NotifyObservers_FullMethodName  = "/wscpb.NodeService/NotifyObservers"
	NodeService_KickUser_FullMethodName         = "/wscpb.NodeService/KickUser"
	NodeService_Ping_FullMethodName             = "/wscpb.NodeService/Ping"
)

// NodeServiceClient is the client API for NodeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// NodeService 节点间 gRPC 通信服务（点对点直连，降低 PubSub 广播延迟）
// [EN] NodeService is the gRPC service for inter-node communication.
type NodeServiceClient interface {
	// SendToUser 向本节点的指定用户发送消息（点对点投递）
	// [EN] Send message to a specific user on this node
	SendToUser(ctx context.Context, in *SendToUserRequest, opts ...grpc.CallOption) (*SendToUserResponse, error)
	// CheckUsersOnline 批量检查用户是否在本节点在线（路由探测）
	// [EN] Batch check if users are online on this node
	CheckUsersOnline(ctx context.Context, in *CheckUsersOnlineRequest, opts ...grpc.CallOption) (*CheckUsersOnlineResponse, error)
	// BroadcastGroup 向本节点的群组成员广播消息
	// [EN] Broadcast message to group members on this node
	BroadcastGroup(ctx context.Context, in *BroadcastGroupRequest, opts ...grpc.CallOption) (*BroadcastGroupResponse, error)
	// NotifyObservers 通知本节点的观察者
	// [EN] Notify observers on this node
	NotifyObservers(ctx context.Context, in *NotifyObserversRequest, opts ...grpc.CallOption) (*NotifyObserversResponse, error)
	// KickUser 踢出本节点上的用户
	// [EN] Kick user on this node
	KickUser(ctx context.Context, in *KickUserRequest, opts ...grpc.CallOption) (*KickUserResponse, error)
	// Ping 节点健康检查
	// [EN] Node health check
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
}

type nodeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeServiceClient(cc grpc.ClientConnInterface) NodeServiceClient {
	return &nodeServiceClient{cc}
}

func (c *nodeServiceClient) SendToUser(ctx context.Context, in *SendToUserRequest, opts ...grpc.CallOption) (*SendToUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendToUserResponse)
	err := c.cc.Invoke(ctx, NodeService_SendToUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) CheckUsersOnline(ctx context.Context, in *CheckUsersOnlineRequest, opts ...grpc.CallOption) (*CheckUsersOnlineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckUsersOnlineResponse)
	err := c.cc.Invoke(ctx, NodeService_CheckUsersOnline_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) BroadcastGroup(ctx context.Context, in *BroadcastGroupRequest, opts ...grpc.CallOption) (*BroadcastGroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BroadcastGroupResponse)
	err := c.cc.Invoke(ctx, NodeService_BroadcastGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) NotifyObservers(ctx context.Context, in *NotifyObserversRequest, opts ...grpc.CallOption) (*NotifyObserversResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NotifyObserversResponse)
	err := c.cc.Invoke(ctx, NodeService_NotifyObservers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) KickUser(ctx context.Context, in *KickUserRequest, opts ...grpc.CallOption) (*KickUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KickUserResponse)
	err := c.cc.Invoke(ctx, NodeService_KickUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, NodeService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodeServiceServer is the server API for NodeService service.
// All implementations must embed UnimplementedNodeServiceServer
// for forward compatibility.
//
// NodeService 节点间 gRPC 通信服务（点对点直连，降低 PubSub 广播延迟）
// [EN] NodeService is the gRPC service for inter-node communication.
type NodeServiceServer interface {
	// SendToUser 向本节点的指定用户发送消息（点对点投递）
	// [EN] Send message to a specific user on this node
	SendToUser(context.Context, *SendToUserRequest) (*SendToUserResponse, error)
	// CheckUsersOnline 批量检查用户是否在本节点在线（路由探测）
	// [EN] Batch check if users are online on this node
	CheckUsersOnline(context.Context, *CheckUsersOnlineRequest) (*CheckUsersOnlineResponse, error)
	// BroadcastGroup 向本节点的群组成员广播消息
	// [EN] Broadcast message to group members on this node
	BroadcastGroup(context.Context, *BroadcastGroupRequest) (*BroadcastGroupResponse, error)
	// NotifyObservers 通知本节点的观察者
	// [EN] Notify observers on this node
	NotifyObservers(context.Context, *NotifyObserversRequest) (*NotifyObserversResponse, error)
	// KickUser 踢出本节点上的用户
	// [EN] Kick user on this node
	KickUser(context.Context, *KickUserRequest) (*KickUserResponse, error)
	// Ping 节点健康检查
	// [EN] Node health check
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	mustEmbedUnimplementedNodeServiceServer()
}

// UnimplementedNodeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNodeServiceServer struct{}

func (UnimplementedNodeServiceServer) SendToUser(context.Context, *SendToUserRequest) (*SendToUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendToUser not implemented")
}
func (UnimplementedNodeServiceServer) CheckUsersOnline(context.Context, *CheckUsersOnlineRequest) (*CheckUsersOnlineResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckUsersOnline not implemented")
}
func (UnimplementedNodeServiceServer) BroadcastGroup(context.Context, *BroadcastGroupRequest) (*BroadcastGroupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BroadcastGroup not implemented")
}
func (UnimplementedNodeServiceServer) NotifyObservers(context.Context, *NotifyObserversRequest) (*NotifyObserversResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method NotifyObservers not implemented")
}
func (UnimplementedNodeServiceServer) KickUser(context.Context, *KickUserRequest) (*KickUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method KickUser not implemented")
}
func (UnimplementedNodeServiceServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedNodeServiceServer) mustEmbedUnimplementedNodeServiceServer() {}
func (UnimplementedNodeServiceServer) testEmbeddedByValue()                     {}

// UnsafeNodeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeServiceServer will
// result in compilation errors.
type UnsafeNodeServiceServer interface {
	mustEmbedUnimplementedNodeServiceServer()
}

func RegisterNodeServiceServer(s grpc.ServiceRegistrar, srv NodeServiceServer) {
	// If the following call panics, it indicates UnimplementedNodeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NodeService_ServiceDesc, srv)
}

func _NodeService_SendToUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendToUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).SendToUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_SendToUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).SendToUser(ctx, req.(*SendToUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_CheckUsersOnline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckUsersOnlineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).CheckUsersOnline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_CheckUsersOnline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).CheckUsersOnline(ctx, req.(*CheckUsersOnlineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_BroadcastGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BroadcastGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).BroadcastGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_BroadcastGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).BroadcastGroup(ctx, req.(*BroadcastGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_NotifyObservers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotifyObserversRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).NotifyObservers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_NotifyObservers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).NotifyObservers(ctx, req.(*NotifyObserversRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_KickUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KickUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).KickUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_KickUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).KickUser(ctx, req.(*KickUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NodeService_ServiceDesc is the grpc.ServiceDesc for NodeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NodeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wscpb.NodeService",
	HandlerType: (*NodeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendToUser",
			Handler:    _NodeService_SendToUser_Handler,
		},
		{
			MethodName: "CheckUsersOnline",
			Handler:    _NodeService_CheckUsersOnline_Handler,
		},
		{
			MethodName: "BroadcastGroup",
			Handler:    _NodeService_BroadcastGroup_Handler,
		},
		{
			MethodName: "NotifyObservers",
			Handler:    _NodeService_NotifyObservers_Handler,
		},
		{
			MethodName: "KickUser",
			Handler:    _NodeService_KickUser_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _NodeService_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "node.proto",
}
