// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.24.3
// source: wsc.proto

package wscpb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// HubMessageProto Hub 消息的 protobuf 表示（用于跨节点高效传输）
// [EN] HubMessageProto is the protobuf representation of a Hub message.
type HubMessageProto struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                                  // 消息ID | [EN] Message ID
	MessageType         string                 `protobuf:"bytes,2,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"`                             // 消息类型 | [EN] Message Type
	Sender              string                 `protobuf:"bytes,3,opt,name=sender,proto3" json:"sender,omitempty"`                                                          // 发送者 | [EN] Sender
	SenderName          string                 `protobuf:"bytes,4,opt,name=sender_name,json=senderName,proto3" json:"sender_name,omitempty"`                                // 发送者名称 | [EN] Sender Name
	SenderType          string                 `protobuf:"bytes,5,opt,name=sender_type,json=senderType,proto3" json:"sender_type,omitempty"`                                // 发送者类型 | [EN] Sender Type
	SenderClient        string                 `protobuf:"bytes,6,opt,name=sender_client,json=senderClient,proto3" json:"sender_client,omitempty"`                          // 发送者客户端 | [EN] Sender Client
	Receiver            string                 `protobuf:"bytes,7,opt,name=receiver,proto3" json:"receiver,omitempty"`                                                      // 接收者 | [EN] Receiver
	ReceiverName        string                 `protobuf:"bytes,8,opt,name=receiver_name,json=receiverName,proto3" json:"receiver_name,omitempty"`                          // 接收者名称 | [EN] Receiver Name
	ReceiverType        string                 `protobuf:"bytes,9,opt,name=receiver_type,json=receiverType,proto3" json:"receiver_type,omitempty"`                          // 接收者类型 | [EN] Receiver Type
	ReceiverClient      string                 `protobuf:"bytes,10,opt,name=receiver_client,json=receiverClient,proto3" json:"receiver_client,omitempty"`                   // 接收者客户端 | [EN] Receiver Client
	ReceiverNode        string                 `protobuf:"bytes,11,opt,name=receiver_node,json=receiverNode,proto3" json:"receiver_node,omitempty"`                         // 接收者节点 | [EN] Receiver Node
	SessionId           string                 `protobuf:"bytes,12,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`                                  // 会话ID | [EN] Session ID
	Content             string                 `protobuf:"bytes,13,opt,name=content,proto3" json:"content,omitempty"`                                                       // 消息内容 | [EN] Content
	Data                *structpb.Struct       `protobuf:"bytes,14,opt,name=data,proto3" json:"data,omitempty"`                                                             // 数据 | [EN] Data
	CreateAt            *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=create_at,json=createAt,proto3" json:"create_at,omitempty"`                                     // 创建时间 | [EN] Create At
	MessageId           string                 `protobuf:"bytes,16,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`                                  // 消息ID | [EN] Message ID
	SeqNo               int64                  `protobuf:"varint,17,opt,name=seq_no,json=seqNo,proto3" json:"seq_no,omitempty"`                                             // 序列号 | [EN] Seq No
	Priority            string                 `protobuf:"bytes,18,opt,name=priority,proto3" json:"priority,omitempty"`                                                     // 优先级 | [EN] Priority
	ReplyToMsgId        string                 `protobuf:"bytes,19,opt,name=reply_to_msg_id,json=replyToMsgId,proto3" json:"reply_to_msg_id,omitempty"`                     // 回复消息ID | [EN] Reply To Msg ID
	RequireAck          bool                   `protobuf:"varint,20,opt,name=require_ack,json=requireAck,proto3" json:"require_ack,omitempty"`                              // 是否需要确认 | [EN] Require Ack
	Source              string                 `protobuf:"bytes,21,opt,name=source,proto3" json:"source,omitempty"`                                                         // 源节点ID | [EN] Source Node ID
	PushType            string                 `protobuf:"bytes,22,opt,name=push_type,json=pushType,proto3" json:"push_type,omitempty"`                                     // 推送类型 | [EN] Push Type
	BroadcastType       string                 `protobuf:"bytes,23,opt,name=broadcast_type,json=broadcastType,proto3" json:"broadcast_type,omitempty"`                      // 广播类型 | [EN] Broadcast Type
	SkipDatabaseStorage bool                   `protobuf:"varint,24,opt,name=skip_database_storage,json=skipDatabaseStorage,proto3" json:"skip_database_storage,omitempty"` // 是否跳过数据库存储 | [EN] Skip Database Storage
	SkipSendToClient    bool                   `protobuf:"varint,25,opt,name=skip_send_to_client,json=skipSendToClient,proto3" json:"skip_send_to_client,omitempty"`        // 是否跳过发送到客户端 | [EN] Skip Send To Client
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *HubMessageProto) Reset() {
	*x = HubMessageProto{}
	mi := &file_wsc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HubMessageProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HubMessageProto) ProtoMessage() {}

func (x *HubMessageProto) ProtoReflect() protoreflect.Message {
	mi := &file_wsc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HubMessageProto.ProtoReflect.Descriptor instead.
func (*HubMessageProto) Descriptor() ([]byte, []int) {
	return file_wsc_proto_rawDescGZIP(), []int{0}
}

func (x *HubMessageProto) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *HubMessageProto) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

func (x *HubMessageProto) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *HubMessageProto) GetSenderName() string {
	if x != nil {
		return x.SenderName
	}
	return ""
}

func (x *HubMessageProto) GetSenderType() string {
	if x != nil {
		return x.SenderType
	}
	return ""
}

func (x *HubMessageProto) GetSenderClient() string {
	if x != nil {
		return x.SenderClient
	}
	return ""
}

func (x *HubMessageProto) GetReceiver() string {
	if x != nil {
		return x.Receiver
	}
	return ""
}

func (x *HubMessageProto) GetReceiverName() string {
	if x != nil {
		return x.ReceiverName
	}
	return ""
}

func (x *HubMessageProto) GetReceiverType() string {
	if x != nil {
		return x.ReceiverType
	}
	return ""
}

func (x *HubMessageProto) GetReceiverClient() string {
	if x != nil {
		return x.ReceiverClient
	}
	return ""
}

func (x *HubMessageProto) GetReceiverNode() string {
	if x != nil {
		return x.ReceiverNode
	}
	return ""
}

func (x *HubMessageProto) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *HubMessageProto) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *HubMessageProto) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *HubMessageProto) GetCreateAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateAt
	}
	return nil
}

func (x *HubMessageProto) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *HubMessageProto) GetSeqNo() int64 {
	if x != nil {
		return x.SeqNo
	}
	return 0
}

func (x *HubMessageProto) GetPriority() string {
	if x != nil {
		return x.Priority
	}
	return ""
}

func (x *HubMessageProto) GetReplyToMsgId() string {
	if x != nil {
		return x.ReplyToMsgId
	}
	return ""
}

func (x *HubMessageProto) GetRequireAck() bool {
	if x != nil {
		return x.RequireAck
	}
	return false
}

func (x *HubMessageProto) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *HubMessageProto) GetPushType() string {
	if x != nil {
		return x.PushType
	}
	return ""
}

func (x *HubMessageProto) GetBroadcastType() string {
	if x != nil {
		return x.BroadcastType
	}
	return ""
}

func (x *HubMessageProto) GetSkipDatabaseStorage() bool {
	if x != nil {
		return x.SkipDatabaseStorage
	}
	return false
}

func (x *HubMessageProto) GetSkipSendToClient() bool {
	if x != nil {
		return x.SkipSendToClient
	}
	return false
}

// DistributedMessageProto 分布式消息（跨节点传输包装）
// [EN] DistributedMessageProto is the protobuf representation of a Distributed message.
type DistributedMessageProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`                         // 操作类型 | [EN] Operation Type
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`       // 源节点ID | [EN] Source Node ID
	TargetId      string                 `protobuf:"bytes,3,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"` // 目标ID（用户ID、节点ID等） | [EN] Target ID
	Message       *HubMessageProto       `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`                   // 消息数据 | [EN] Message Data
	Reason        string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`                     // 原因 | [EN] Reason
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`               // 时间戳 | [EN] Timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DistributedMessageProto) Reset() {
	*x = DistributedMessageProto{}
	mi := &file_wsc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DistributedMessageProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DistributedMessageProto) ProtoMessage() {}

func (x *DistributedMessageProto) ProtoReflect() protoreflect.Message {
	mi := &file_wsc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DistributedMessageProto.ProtoReflect.Descriptor instead.
func (*DistributedMessageProto) Descriptor() ([]byte, []int) {
	return file_wsc_proto_rawDescGZIP(), []int{1}
}

func (x *DistributedMessageProto) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *DistributedMessageProto) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *DistributedMessageProto) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *DistributedMessageProto) GetMessage() *HubMessageProto {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *DistributedMessageProto) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *DistributedMessageProto) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// NodeInfoProto 节点信息（用于 Redis 存储和跨节点发现）
// [EN] NodeInfoProto is the protobuf representation of a Node info.
type NodeInfoProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                  // 节点ID | [EN] Node ID
	IpAddress     string                 `protobuf:"bytes,2,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`   // IP地址 | [EN] IP Address
	Port          int32                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`                             // 端口号 | [EN] Port
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`                          // 状态 | [EN] Status
	LoadScore     float64                `protobuf:"fixed64,5,opt,name=load_score,json=loadScore,proto3" json:"load_score,omitempty"` // 负载分数 | [EN] Load Score
	LastSeen      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`      // 最后一次看到时间 | [EN] Last Seen
	Connections   int64                  `protobuf:"varint,7,opt,name=connections,proto3" json:"connections,omitempty"`               // 连接数 | [EN] Connections
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeInfoProto) Reset() {
	*x = NodeInfoProto{}
	mi := &file_wsc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfoProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfoProto) ProtoMessage() {}

func (x *NodeInfoProto) ProtoReflect() protoreflect.Message {
	mi := &file_wsc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfoProto.ProtoReflect.Descriptor instead.
func (*NodeInfoProto) Descriptor() ([]byte, []int) {
	return file_wsc_proto_rawDescGZIP(), []int{2}
}

func (x *NodeInfoProto) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NodeInfoProto) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *NodeInfoProto) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *NodeInfoProto) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *NodeInfoProto) GetLoadScore() float64 {
	if x != nil {
		return x.LoadScore
	}
	return 0
}

func (x *NodeInfoProto) GetLastSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeen
	}
	return nil
}

func (x *NodeInfoProto) GetConnections() int64 {
	if x != nil {
		return x.Connections
	}
	return 0
}

var File_wsc_proto protoreflect.FileDescriptor

const file_wsc_proto_rawDesc = "" +
	"\n" +
	"\twsc.proto\x12\x03wsc\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xef\x06\n" +
	"\x0fHubMessageProto\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fmessage_type\x18\x02 \x01(\tR\vmessageType\x12\x16\n" +
	"\x06sender\x18\x03 \x01(\tR\x06sender\x12\x1f\n" +
	"\vsender_name\x18\x04 \x01(\tR\n" +
	"senderName\x12\x1f\n" +
	"\vsender_type\x18\x05 \x01(\tR\n" +
	"senderType\x12#\n" +
	"\rsender_client\x18\x06 \x01(\tR\fsenderClient\x12\x1a\n" +
	"\breceiver\x18\a \x01(\tR\breceiver\x12#\n" +
	"\rreceiver_name\x18\b \x01(\tR\freceiverName\x12#\n" +
	"\rreceiver_type\x18\t \x01(\tR\freceiverType\x12'\n" +
	"\x0freceiver_client\x18\n" +
	" \x01(\tR\x0ereceiverClient\x12#\n" +
	"\rreceiver_node\x18\v \x01(\tR\freceiverNode\x12\x1d\n" +
	"\n" +
	"session_id\x18\f \x01(\tR\tsessionId\x12\x18\n" +
	"\acontent\x18\r \x01(\tR\acontent\x12+\n" +
	"\x04data\x18\x0e \x01(\v2\x17.google.protobuf.StructR\x04data\x127\n" +
	"\tcreate_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\bcreateAt\x12\x1d\n" +
	"\n" +
	"message_id\x18\x10 \x01(\tR\tmessageId\x12\x15\n" +
	"\x06seq_no\x18\x11 \x01(\x03R\x05seqNo\x12\x1a\n" +
	"\bpriority\x18\x12 \x01(\tR\bpriority\x12%\n" +
	"\x0freply_to_msg_id\x18\x13 \x01(\tR\freplyToMsgId\x12\x1f\n" +
	"\vrequire_ack\x18\x14 \x01(\bR\n" +
	"requireAck\x12\x16\n" +
	"\x06source\x18\x15 \x01(\tR\x06source\x12\x1b\n" +
	"\tpush_type\x18\x16 \x01(\tR\bpushType\x12%\n" +
	"\x0ebroadcast_type\x18\x17 \x01(\tR\rbroadcastType\x122\n" +
	"\x15skip_database_storage\x18\x18 \x01(\bR\x13skipDatabaseStorage\x12-\n" +
	"\x13skip_send_to_client\x18\x19 \x01(\bR\x10skipSendToClient\"\xe5\x01\n" +
	"\x17DistributedMessageProto\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x1b\n" +
	"\ttarget_id\x18\x03 \x01(\tR\btargetId\x12.\n" +
	"\amessage\x18\x04 \x01(\v2\x14.wsc.HubMessageProtoR\amessage\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\x128\n" +
	"\ttimestamp\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xe4\x01\n" +
	"\rNodeInfoProto\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x02 \x01(\tR\tipAddress\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"load_score\x18\x05 \x01(\x01R\tloadScore\x127\n" +
	"\tlast_seen\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\blastSeen\x12 \n" +
	"\vconnections\x18\a \x01(\x03R\vconnectionsB,Z*github.com/kamalyes/go-wsc/models/pb;wscpbb\x06proto3"

var (
	file_wsc_proto_rawDescOnce sync.Once
	file_wsc_proto_rawDescData []byte
)

func file_wsc_proto_rawDescGZIP() []byte {
	file_wsc_proto_rawDescOnce.Do(func() {
		file_wsc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wsc_proto_rawDesc), len(file_wsc_proto_rawDesc)))
	})
	return file_wsc_proto_rawDescData
}

var file_wsc_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_wsc_proto_goTypes = []any{
	(*HubMessageProto)(nil),         // 0: wsc.HubMessageProto
	(*DistributedMessageProto)(nil), // 1: wsc.DistributedMessageProto
	(*NodeInfoProto)(nil),           // 2: wsc.NodeInfoProto
	(*structpb.Struct)(nil),         // 3: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil),   // 4: google.protobuf.Timestamp
}
var file_wsc_proto_depIdxs = []int32{
	3, // 0: wsc.HubMessageProto.data:type_name -> google.protobuf.Struct
	4, // 1: wsc.HubMessageProto.create_at:type_name -> google.protobuf.Timestamp
	0, // 2: wsc.DistributedMessageProto.message:type_name -> wsc.HubMessageProto
	4, // 3: wsc.DistributedMessageProto.timestamp:type_name -> google.protobuf.Timestamp
	4, // 4: wsc.NodeInfoProto.last_seen:type_name -> google.protobuf.Timestamp
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_wsc_proto_init() }
func file_wsc_proto_init() {
	if File_wsc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wsc_proto_rawDesc), len(file_wsc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wsc_proto_goTypes,
		DependencyIndexes: file_wsc_proto_depIdxs,
		MessageInfos:      file_wsc_proto_msgTypes,
	}.Build()
	File_wsc_proto = out.File
	file_wsc_proto_goTypes = nil
	file_wsc_proto_depIdxs = nil
}
